### ISSUE TITLE
ER図作成

### ISSUE THREAD

**Issue by ntakashima** [yuzuki-aritomo/ReserveTaskBackend#1]
下記フォルダにdaraw.ioにて作成したer図を置いてあります。

https://drive.google.com/drive/folders/1VM7UUlWDiUYUB6ZXrac0AONlBy83QEXA?usp=sharing

**Comment by ntakashima** [comment]
@yuzuki-aritomo 
口頭で話していた通り、勘違いしてました！
2テーブルで問題ないです。

ただ、confirm_reserve で can_reserve_id を持っているので、confirm_reserve テーブルには fp_id は不要じゃないでしょうか？そうすると user_id が2つになる問題もなくなります。

**Comment by yuzuki-aritomo** [comment]
なるほど、了解です！user_idのみ持たせて修正します！
